// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  log_in: dynamic(() => import("./LogIn")),
  services: dynamic(() => import("./AnySize")),
  tag_list: dynamic(() => import("./TagList")),
  team: dynamic(() => import("./Team")),
};
